#!/usr/bin/env bash
# Prints FizzBuzz from 1 to 100, separated by spaces on a single line.
for i in {1..100}
do
    if [ $((i % 15)) -eq 0 ]
    then
        echo -n "FizzBuzz "
    elif [ $((i % 3)) -eq 0 ]
    then
        echo -n "Fizz "
    elif [ $((i % 5)) -eq 0 ]
    then
        echo -n "Buzz "
    else
        echo -n "$i "
    fi
done
echo
