#!/usr/bin/env bash
# Loops 1..10 using a while loop and a case statement.
i=1
while [ "$i" -le 10 ]
do
    case "$i" in
        4)
            echo "bad luck"
            ;;
        8)
            echo "good luck"
            ;;
        *)
            echo "Best School"
            ;;
    esac
    i=$((i + 1))
done
