#!/usr/bin/env bash
# Loops 1..10: 4 -> bad luck, 8 -> good luck, otherwise the number.
for i in {1..10}
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo $i
    fi
done
