#!/usr/bin/env bash
# Lists numbers 1..20 with superstition messages for 4, 9, and 17.
for i in {1..20}
do
    echo $i
    if [ $i -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
done
