#!/usr/bin/env bash
# Gives information about the file "school" in the current directory.
if [ -e school ]
then
    echo "school file exists"
    if [ -d school ]
    then
        echo "school is a directory"
    fi
    if [ -s school ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f school ]
    then
        echo "school is a regular file"
    else
        echo "school is not a regular file"
    fi
else
    echo "school file does not exist"
fi
